config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "restaurants#index"
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :category, inclusion: { in: %w(chinese italian japanese french belgian), message: "%{value} is not a valid category" }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [ :show, :edit, :update, :destroy ]

  def index
    @restaurants =  Restaurant.all
  end

  def top
    @restaurants = Restaurant.where(stars: 5)
    render :index
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant

  def new
    @review = Review.new # This is needed for simple_form
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant

    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <div class="navbar-wagon">
      <!-- Right Navigation -->
      <div class="navbar-wagon-right hidden-xs hidden-sm">
        <!-- Links -->
        <%= link_to "Home", root_path, class: "navbar-wagon-item navbar-wagon-link" %>
      </div>
    </div>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<div class="col-sm-6 col-sm-offset-3">
  <%= simple_form_for restaurant do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :category %>
    <%= f.input :phone_number %>
    <%= f.submit %>
  <% end %>
</div>

app/views/restaurants/edit.html.erb
<h1>Edit This Restaurant</h1>

<%= render "form", restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<h2>Restaurants</h2>

<p><%= link_to "Add your restaurant", new_restaurant_path %></p>

<% @restaurants.each do |restaurant| %>
  <h3><%= link_to restaurant.name, restaurant_path(restaurant) %></h3>
  <p>Category: <%= restaurant.category %></p>
  <%= link_to "Edit", edit_restaurant_path(restaurant) %> | <%= link_to "Remove", restaurant_path(restaurant), method: :delete %>
<% end %>

app/views/restaurants/new.html.erb
<h1>Add a New Restaurant</h1>

<%= render "form", restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %></h2>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.category %></p>
<p><%= @restaurant.phone_number %></p>

<p><%= link_to "Leave a review", new_restaurant_review_path(@restaurant) %></p>
<p><%= link_to "Back Home", restaurants_path %></p>
<p><%= link_to "Edit", edit_restaurant_path(@restaurant) %></p>

<h3>HERE ARE ALL THE REVIEWS:</h3>
<ul>
  <% @restaurant.reviews.each do |review| %>
    <li><%= review.content %></li>
  <% end %>
</ul>

app/views/reviews/new.html.erb
<h1>Create a new review</h1>

<%= simple_form_for([@restaurant, @review]) do |f| %>
  <%= f.input :content, label: 'What did you think?' %>
  <%= f.input :rating, label: 'On a scale of 1 to 5?' %>
  <%= f.submit %>
<% end %>